const String inputIdEvent = 'Введите ID мероприятия';
const String idPlaceholder = '012-345-def';
const String join = 'Присоединиться';
const String createEvent = 'Создать мероприятие';
const String or = 'или';
const String yourName = 'Ваше имя ?';
const String cancel = 'Отмена';
const String errorEventIdFormat = 'Неправильный ID (формат: $idPlaceholder)';
const String errorNameEmpty = 'Не забудте ввести имя';