name: mobile
description: application for events support

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_redux: ^0.5.3
  redux: ^3.0.0
  redux_epics: ^0.10.6
  url_launcher: ^5.0.2
  http: ^0.12.0+2
  api_models:
    path: ../api_models
  flutter_document_picker: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  json_serializable: any
  flutter_launcher_icons: ^0.7.1
  pedantic: ^1.5.0

flutter_icons:
  ios: true
  android: true
  image_path: asset/image/icon/icon.png

flutter:
  uses-material-design: true
  assets:
    - asset/image/icon/icon.png